// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://iutxzuwexyiggenuebxw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml1dHh6dXdleHlpZ2dlbnVlYnh3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE2MTUzNjIsImV4cCI6MjA3NzE5MTM2Mn0.i1-eAiUQcHUE3quzTiOg7kJcehLkLl-DIiSUxPcFWBM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);